### PR TITLE
Quotes

### PR DESCRIPTION
**Pull request by drewbarontini**
**Status**: Ready to go!

### CODE REVIEW

**Comment by drewbarontini** [comment]
I know I know. I'll finish it! :smile:

**Comment by drewbarontini** [comment]
@katiedelfin Should be ready now. However, I'll probably need your help adding uphearts to quotes. It looks to be tied to compliments right now, so I didn't want to muck around with anything :smile:

**Comment by drewbarontini** [comment]
The only other issue is that the quote is tied to the person that's being quoted, but I'm not storing who is the one quoting, so that might be worth changing, too.

**Comment by yassskitt** [comment]
Yay! So... what if, instead of uphearts, we just use emoji reactions for :allthethings:? See #4.

Also, yeah, would be nice to store who was adding the quote.

**Comment by drewbarontini** [comment]
That's awesome!

**Comment by drewbarontini** [comment]
Okay, @katiedelfin - this stores both the person being quoted and the person quoting, and the setup reflects what you did for compliments. That _should_ be it now.

**Comment by drewbarontini** [comment]
I know it might mess stuff up, but we could change the URL to `chatter.preschool.io` to fit with both compliments and quotes. Not a big deal, though :wink:

**Comment by yassskitt** [comment]
Oooh, yes. On it.

**Pull request merged**
